--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/amos/wallpapers/44.jpg"

-- Special
background="#081933"
foreground="#a5b8c1"
cursor="#a5b8c1"

-- Colors
color0="#081933"
color1="#9B5377"
color2="#E75C5B"
color3="#123D86"
color4="#195E81"
color5="#355982"
color6="#506885"
color7="#a5b8c1"
color8="#738087"
color9="#9B5377"
color10="#E75C5B"
color11="#123D86"
color12="#195E81"
color13="#355982"
color14="#506885"
color15="#a5b8c1"
