# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/amos/wallpapers/44.jpg'

# Special
background='#081933'
foreground='#a5b8c1'
cursor='#a5b8c1'

# Colors
color0='#081933'
color1='#9B5377'
color2='#E75C5B'
color3='#123D86'
color4='#195E81'
color5='#355982'
color6='#506885'
color7='#a5b8c1'
color8='#738087'
color9='#9B5377'
color10='#E75C5B'
color11='#123D86'
color12='#195E81'
color13='#355982'
color14='#506885'
color15='#a5b8c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
